"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ha young Kim",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen flex-col items-center justify-center bg-slate-900">{children}</main>
      </body>
    </html>
  );
}
